spring.application.name=ride-management-backend
server.port=8099

spring.datasource.url=jdbc:postgresql://localhost:5432/ride_management_db
spring.datasource.username=ride_user
spring.datasource.password=ride_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=change-this-secret-for-production-campus-ride-management
app.jwt.expiration-ms=86400000
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173,http://[::1]:5173
